API-000: Medication Dispense Transformer Dosage
department-of-veterans-affairs/health-apis-vista-fhir-query pull request #402
Opened 2022-02-11 16:07 UTC by msilverman-va

Add dosage instruction to medication dispense    

Co-authored-by: Joshua Miller <jmiller@rise8.us>

2022-02-14 19:46 UTC, bschofield-va commented on vista-fhir-query/src/main/java/gov/va/api/health/vistafhirquery/service/controller/medicationdispense/R4MedicationDispenseTransformer.java
> +    return Dosage.builder()
We should not emit an empty `Dosage`. If you can't populate a useful structure, do nothing.

2022-02-14 19:47 UTC, bschofield-va commented on vista-fhir-query/src/test/java/gov/va/api/health/vistafhirquery/service/controller/medicationdispense/R4MedicationDispenseTransformerTest.java
> +  void toFhir_no_dosage_instructions() {
please use our naming conventions for tests

2022-02-14 21:36 UTC, bschofield-va commented on vista-fhir-query/src/main/java/gov/va/api/health/vistafhirquery/service/controller/medicationdispense/R4MedicationDispenseTransformer.java
> +        .text(Objects.toString(sig, ""))
You've already established these values are not null... no need for `Objects.toString`

2022-02-14 21:37 UTC, kivarsson-va commented on vista-fhir-query/src/main/java/gov/va/api/health/vistafhirquery/service/controller/medicationdispense/R4MedicationDispenseTransformer.java
> +        .text(Objects.toString(sig, ""))
the check was if they're both null to not return an empty dosage. one or the other could still be empty

2022-02-14 21:45 UTC, bschofield-va commented on vista-fhir-query/src/test/java/gov/va/api/health/vistafhirquery/service/controller/medicationdispense/MedicationDispenseSamples.java
> +    public VprGetPatientData.Response.Results resultsWithNoPatientInstructions2() {
I don't think this is a sustainable approach to add _every_ sample a particular test might need to class, especially when named so ambiguously...

A slightly better approach would be to move these _customized_ sample values to the test that needs them.

A 10/10 approach would be to make the specific transformer methods `package` protected and test those specifically.

```
static Stream<Argument> dosageInstruction() {
   return Stream.of(
       Argument.of(null,null,null),
       Argument.of("","",null),
       Argument.of("a","b",Dosage.builder()....whatever...asList(),
       ... more cases here ...
       );
}

@ParameterizedTest @MethdSource void dosageInstruction(String sig, String ptInstructions, List<Dosage> expected) {
  var actual = _transormer().dosageInstruction(sig, ptInstructions);
   assertThat(actual).isEqualTo(expected)
}
```

2022-02-14 21:48 UTC, bschofield-va commented on vista-fhir-query/src/main/java/gov/va/api/health/vistafhirquery/service/controller/medicationdispense/R4MedicationDispenseTransformer.java
> +        .text(Objects.toString(sig, ""))
right .. right, sorry, still do not need emit `""` values, e.g. `"text": ""` is less good than `< text not emitted >`

2022-02-14 21:48 UTC, jhulbert-va commented on vista-fhir-query/src/main/java/gov/va/api/health/vistafhirquery/service/controller/medicationdispense/R4MedicationDispenseTransformer.java
> +    if (isBlank(sig) && isBlank(ptInstructions)) {
The `R4Transformers` class also has an `allBlank()`that can accomplish this.

2022-02-14 21:49 UTC, bschofield-va commented on vista-fhir-query/src/main/java/gov/va/api/health/vistafhirquery/service/controller/medicationdispense/R4MedicationDispenseTransformer.java
> +        .text(Objects.toString(sig, ""))
Sorry... that ^ might not be clear...

Should not do this:
```
  {  "text": "", "patientInstruction": "stuff" }
```
Instead do this:
```
  {  "patientInstruction": "stuff" }
```

2022-02-14 22:15 UTC, kivarsson-va commented on vista-fhir-query/src/test/java/gov/va/api/health/vistafhirquery/service/controller/medicationdispense/MedicationDispenseSamples.java
> +    public VprGetPatientData.Response.Results resultsWithNoPatientInstructions2() {
we don't test many different cases for each field so the parameterized tests might be a little verbose. agree the resources for specific tests can be moved into the respective tests, though 👌

2022-02-14 22:30 UTC, bschofield-va commented on vista-fhir-query/src/test/java/gov/va/api/health/vistafhirquery/service/controller/medicationdispense/MedicationDispenseSamples.java
> +    public VprGetPatientData.Response.Results resultsWithNoPatientInstructions2() {
we do in other places, and this transformer will ultimately be upgraded to so, too.
in general, I prefer to test the smaller transformations specifically vs. using something big like `toFhir()` to verify a small change to some nested object,

2022-02-14 22:31 UTC, bschofield-va commented on vista-fhir-query/src/main/java/gov/va/api/health/vistafhirquery/service/controller/medicationdispense/R4MedicationDispenseTransformer.java
> +   */
while you're here.... can you make `med.fill().stream()` be `Safe.stream(med.fill())`?

2022-02-14 22:36 UTC, kivarsson-va commented on vista-fhir-query/src/test/java/gov/va/api/health/vistafhirquery/service/controller/medicationdispense/MedicationDispenseSamples.java
> +    public VprGetPatientData.Response.Results resultsWithNoPatientInstructions2() {
we were trying to avoid having to make them all public, but if y'all would prefer us to do it that way we can do that

2022-02-16 18:44 UTC, bschofield-va requested changes
blocking merge

2022-02-17 01:07 UTC, bschofield-va commented on vista-fhir-query/src/test/java/gov/va/api/health/vistafhirquery/service/controller/medicationdispense/MedicationDispenseSamples.java
> +    public VprGetPatientData.Response.Results resultsWithNoPatientInstructions2() {
I refactored the tests to have more focus. `package` protection is a reasonable compromise between `public` and `private`_-but-not-easily-testable_ protection.

2022-02-17 01:08 UTC, bschofield-va approved these changes

2022-02-17 01:08 UTC, merged