API 13157 Populate Participant Location Appointment
department-of-veterans-affairs/health-apis-vista-fhir-query pull request #403
Opened 2022-02-11 16:16 UTC by agarcia-va

2022-02-11 16:19 UTC, taylorrassmannlibertyits commented on vista-fhir-query/src/main/java/gov/va/api/health/vistafhirquery/service/controller/appointment/R4AppointmentTransformer.java
> +        .status(Appointment.ParticipationStatus.accepted)
Are we sure this field needs to be populated?

2022-02-11 16:36 UTC, agarcia-va commented on vista-fhir-query/src/main/java/gov/va/api/health/vistafhirquery/service/controller/appointment/R4AppointmentTransformer.java
> +        .status(Appointment.ParticipationStatus.accepted)
Yes, status is defined as not null. Not doing so causes IT failures. I went with the assumption that if the Appointment is registered, the location would already need to be confirmed, so `accepted` was appropriate.

2022-02-11 17:55 UTC, ilaflamme-va commented on vista-fhir-query/src/main/java/gov/va/api/health/vistafhirquery/service/controller/appointment/R4AppointmentTransformer.java
> +        .status(Appointment.ParticipationStatus.accepted)
It's dangerous to _assume_ these kind of things, as developers. I highly recommend confirming with KBS (or whoever your source of truth is).

2022-02-11 18:05 UTC, agarcia-va commented on vista-fhir-query/src/main/java/gov/va/api/health/vistafhirquery/service/controller/appointment/R4AppointmentTransformer.java
> +        .status(Appointment.ParticipationStatus.accepted)
@ilaflamme-va Noted, I will re-check this. I did not see any case where location was saved as anything else, but I will confirm this is the case and report again in this thread.

2022-02-11 18:09 UTC, agarcia-va commented on vista-fhir-query/src/main/java/gov/va/api/health/vistafhirquery/service/controller/appointment/R4AppointmentTransformer.java
> +        .status(Appointment.ParticipationStatus.accepted)
@ilaflamme-va I verified from the `lighthouse-charon` [wiki's mapping notes](https://github.com/department-of-veterans-affairs/lighthouse-charon/wiki/Incubator:-VPR-GET-PATIENT-DATA-(Appointment)-to-R4-Appointment#patient-participant). It does not specify about `location`, but `Appointment.Participant`'s mapping does default to `accepted` in its `status`, so the same should hold true for `location`. Both would be participants, after all.

2022-02-14 20:03 UTC, bschofield-va commented on vista-fhir-query/src/main/java/gov/va/api/health/vistafhirquery/service/controller/appointment/R4AppointmentTransformer.java
> +    var participants = List.of(participants(), location(rpcAppointment.facility()));
^ this... keep decision making together and maintain the same level of abstraction with in a method.

2022-02-14 20:38 UTC, jblefkove-va commented on vista-fhir-query/src/main/java/gov/va/api/health/vistafhirquery/service/controller/appointment/R4AppointmentTransformer.java
> +    var participants = List.of(participants(), location(rpcAppointment.facility()));
Yes... it is also odd to have a plural `participants()` method returning a single participant

2022-02-14 20:39 UTC, jblefkove-va commented on vista-fhir-query/src/main/java/gov/va/api/health/vistafhirquery/service/controller/appointment/R4AppointmentTransformer.java
> +        .status(Appointment.ParticipationStatus.accepted)
We assume `accepted` status for both patient and location participants in data-query, so I think it's reasonable to do the same here

2022-02-14 20:42 UTC, jblefkove-va commented on vista-fhir-query/src/main/java/gov/va/api/health/vistafhirquery/service/controller/appointment/R4AppointmentTransformer.java
> +    var display = "vha_" + site + "_" + facilityIen;
`facilityIen` is the VistA site ID, not the location IEN. Take a look at [this example](https://github.com/department-of-veterans-affairs/lighthouse-charon/blob/main/charon-models/src/test/resources/SampleAppointmentsResult.xml); the location IEN is `23`, which you have to parse out of `id.value`

2022-02-15 20:37 UTC, jblefkove-va commented on vista-fhir-query/src/main/java/gov/va/api/health/vistafhirquery/service/controller/appointment/R4AppointmentTransformer.java
> +        .participant(participants(rpcAppointment))
if `id` is the only field used, why not pass that in here?

2022-02-15 20:39 UTC, jblefkove-va commented on vista-fhir-query/src/main/java/gov/va/api/health/vistafhirquery/service/controller/appointment/R4AppointmentTransformer.java
> +        location(rpcAppointment.id()));
There needs to be protection here against `location()` returning null

2022-02-15 20:40 UTC, jblefkove-va commented on vista-fhir-query/src/main/java/gov/va/api/health/vistafhirquery/service/controller/appointment/R4AppointmentTransformer.java
> +    var locationIen = id.value().substring(id.value().lastIndexOf(";") + 1);
probably also worth checking that `locationIen` is not blank

2022-02-16 16:45 UTC, jblefkove-va submitted a review, later dismissed
:shipit:

2022-02-16 18:43 UTC, bschofield-va requested changes
blocking merge

2022-02-16 21:20 UTC, bschofield-va commented on vista-fhir-query/src/main/java/gov/va/api/health/vistafhirquery/service/controller/appointment/R4AppointmentTransformer.java
> +    participants.add(participantPatient());
@agarcia-va Note the change here where I normalize the level of abstraction in this method. It now delegates to two helpers instead of one helper and building one participant by hand.

2022-02-16 21:21 UTC, bschofield-va commented on vista-fhir-query/src/main/java/gov/va/api/health/vistafhirquery/service/controller/appointment/R4AppointmentTransformer.java
> +    var facilitiesApiIdentifier = "vha_" + site + "_" + locationIen;
@agarcia-va note the explanation as _why_ we format the ID this way

2022-02-16 21:22 UTC, bschofield-va commented on vista-fhir-query/src/main/java/gov/va/api/health/vistafhirquery/service/controller/appointment/R4AppointmentTransformer.java
> +  String locationIenFrom(ValueOnlyXmlAttribute id) {
@agarcia-va Note the extraction of location IEN parsing to it's own method. Also note the example in the comment so future stewards understand what kind of ID we were trying to parse. Finally note the handling of some edge case where the last character was a semicolon. The previous version would IndexOutOfBounds.

2022-02-16 21:23 UTC, bschofield-va approved these changes

2022-02-16 21:24 UTC, merged