API-13384-effective-and-expiration-date
department-of-veterans-affairs/health-apis-vista-fhir-query pull request #405
Opened 2022-02-14 20:10 UTC by jhulbert-va

# [API-13384](https://vajira.max.gov/browse/API-13384)

2022-02-14 20:45 UTC, jabando-va commented on vista-fhir-query/src/main/java/gov/va/api/health/vistafhirquery/service/controller/coverage/InsuranceBufferToR4CoverageTransformer.java
> +        .internal(InsuranceVerificationProcessor.EFFECTIVE_DATE, this::toFilemanDate)
I think that field number needs to be added to `MAPPED_VISTA_FIELDS`. Same for `EXPIRATION_DATE`.

2022-02-14 21:34 UTC, jabando-va approved these changes

2022-02-15 14:11 UTC, bschofield-va commented on vista-fhir-query/src/main/java/gov/va/api/health/vistafhirquery/service/controller/R4Transformers.java
> +  public static boolean isStringCorrectLength(int min, int max, String value) {
Still trying to put my finger on why I dislike this method... perhaps it's the name, `correct` implies a right/wrong without the context in which we are asking the question. Perhaps it's the generic `min` and `max` which do not help me understand if the range is inclusive or exclusive of these values. Perhaps it's because it could be rewritten as a one-liner, e.g.,
```
boolean isStringLengthInRangeInclusively(int inclusiveMin, int inclusiveMax, String maybeString) {
  return Range.between(inclusiveMin, inclusiveMax).contains(StringUtils.length(maybeString));
}
```

2022-02-15 14:13 UTC, bschofield-va commented on vista-fhir-query/src/main/java/gov/va/api/health/vistafhirquery/service/controller/R4Transformers.java
> +    return toHumanDateTime(filemanDateTime.value(), ZoneId.of("UTC"));
we're defining the default zone of `UTC` in two different places, perhaps `toHumanDate(filemanDateTime.value())` is more appropriate?

2022-02-15 14:13 UTC, bschofield-va commented on vista-fhir-query/src/main/java/gov/va/api/health/vistafhirquery/service/controller/RequestPayloadExceptions.java
> +          "Value must be between "
inclusively or exclusively?

2022-02-15 21:54 UTC, eclendenning-va approved these changes

2022-02-16 18:44 UTC, bschofield-va requested changes
blocking merge

2022-02-17 19:20 UTC, bschofield-va approved these changes

2022-02-17 20:35 UTC, merged