MedicationRequest steel thread
department-of-veterans-affairs/health-apis-vista-fhir-query pull request #406
Opened 2022-02-15 14:31 UTC by kivarsson-va

# AFTER https://github.com/department-of-veterans-affairs/health-apis-vista-fhir-query/pull/412

Co-authored-by: Kira Ivarsson <kivarsson@rise8.us>
Co-authored-by: Michael Silverman <msilverman@rise8.us>

2022-02-16 18:45 UTC, bschofield-va reviewed
blocking merge

2022-02-16 18:45 UTC, bschofield-va requested changes
blocking merge

2022-02-17 04:29 UTC, bschofield-va commented on vista-fhir-query-tests/src/main/java/gov/va/api/health/vistafhirquery/tests/SystemDefinitions.java
> +        .medicationRequest("I3-vBeIONImGXIKLsJU74tnViW0QxjDZINHOiE0kw25v9c")
This ID will be incorrect in QA, Staging Lab, and Lab. I'm 99.9% sure it will `I3-GTBBRHbarRNLFP8vUaCBY64wGpN0TxB7HWsJxJNbhuu`

2022-02-17 04:31 UTC, bschofield-va commented on vista-fhir-query-tests/src/test/java/gov/va/api/health/vistafhirquery/tests/r4/MedicationRequestIT.java
> +    assumeEnvironmentIn(Environment.LOCAL);
after the first successful deployment into QA, we'll need to turn these on for all synthetic environments.
after the first successful deployment into Production, we'll need to turn it on there, too.

2022-02-17 04:34 UTC, bschofield-va commented on vista-fhir-query/src/main/java/gov/va/api/health/vistafhirquery/service/api/R4MedicationRequestApi.java
> +      tags = {"Medication Request"})
`MedicationRequest` instead of `Medication Request` (we missed this in Medication Dispense. I fixed in another PR)

2022-02-17 04:51 UTC, bschofield-va commented on vista-fhir-query/src/test/java/gov/va/api/health/vistafhirquery/service/controller/medicationrequest/MedicationRequestSamples.java
> +  public static class Vista {
too much duplication between MedicationDispense.Vista, these will need to combine

2022-02-17 11:49 UTC, kivarsson-va commented on vista-fhir-query-tests/src/main/java/gov/va/api/health/vistafhirquery/tests/SystemDefinitions.java
> +        .medicationRequest("I3-vBeIONImGXIKLsJU74tnViW0QxjDZINHOiE0kw25v9c")
out of curiosity, how did you get that ID? we're using the script for the local one, but weren't sure for the others

2022-02-21 16:32 UTC, bschofield-va approved these changes

2022-02-21 16:32 UTC, merged